// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	authservice "github.com/rokwire/rokwire-sdk-go/services/core/auth/authservice"
	mock "github.com/stretchr/testify/mock"
)

// ServiceRegLoader is an autogenerated mock type for the ServiceRegLoader type
type ServiceRegLoader struct {
	mock.Mock
	authService *authservice.AuthService
	*authservice.ServiceRegSubscriptions
}

// LoadServices provides a mock function with given fields:
func (_m *ServiceRegLoader) LoadServices() ([]authservice.ServiceReg, error) {
	ret := _m.Called()

	var r0 []authservice.ServiceReg
	if rf, ok := ret.Get(0).(func() []authservice.ServiceReg); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]authservice.ServiceReg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewServiceRegLoader(authService *authservice.AuthService, subscribedServices []string) *ServiceRegLoader {
	subscriptions := authservice.NewServiceRegSubscriptions(subscribedServices)
	return &ServiceRegLoader{authService: authService, ServiceRegSubscriptions: subscriptions}
}
