// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	auth "github.com/rokwire/rokwire-sdk-go/services/core/auth"
	mock "github.com/stretchr/testify/mock"
)

// ServiceRegLoader is an autogenerated mock type for the ServiceRegLoader type
type ServiceRegLoader struct {
	mock.Mock
	authService *auth.Service
	*auth.ServiceRegSubscriptions
}

// LoadServices provides a mock function with given fields:
func (_m *ServiceRegLoader) LoadServices() ([]auth.ServiceReg, error) {
	ret := _m.Called()

	var r0 []auth.ServiceReg
	if rf, ok := ret.Get(0).(func() []auth.ServiceReg); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.ServiceReg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewServiceRegLoader(authService *auth.Service, subscribedServices []string) *ServiceRegLoader {
	subscriptions := auth.NewServiceRegSubscriptions(subscribedServices)
	return &ServiceRegLoader{authService: authService, ServiceRegSubscriptions: subscriptions}
}
