// Code generated by api-generator DO NOT EDIT.
package common

import (
	"github.com/rokwire/rokwire-building-block-sdk-go/services/core/auth/tokenauth"
)

// Default exposes default APIs to the driver adapters
type Default interface {
	// string

	GetVersion() (*string, error)
}

// Admin exposes administrative APIs to the driver adapters
type Admin interface {
	// Config

	GetConfigs(claims *tokenauth.Claims, configType *string) ([]Config, error)
	CreateConfig(claims *tokenauth.Claims, item Config) (*Config, error)
	GetConfig(claims *tokenauth.Claims, id string) (*Config, error)
	UpdateConfig(claims *tokenauth.Claims, id string, item Config) (*Config, error)
	DeleteConfig(claims *tokenauth.Claims, id string) error
}
