openapi: 3.0.3
info:
  title: Rokwire Building Block SDK
  description: Rokwire Building Block SDK API Documentation
  version: 1.6.1
tags:
  - name: Admin
    description: Clients administration applications APIs.
  - name: Default
    description: Default APIs.
paths:
  /version:
    get:
      tags:
        - Default
      summary: Get version
      description: |
        Gets current version of this service
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: v1.0.0
        '500':
          description: Internal error
      x-core-function: GetVersion
      x-data-type: string
  /api/admin/configs:
    get:
      tags:
        - Admin
      summary: Get configs
      description: |
        Get existing configs by search parameters

        **Auth:** Requires valid admin token with one of the following permissions:
        - `get_configs_<name>`
        - `update_configs_<name>`
        - `delete_configs_<name>`
        - `all_configs_<name>`
      security:
        - bearerAuth: []
      parameters:
        - name: config_type
          in: query
          description: config type
          required: false
          style: form
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Config'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-core-function: GetConfigs
      x-data-type: common.Config
      x-authentication-type: Permissions
    post:
      tags:
        - Admin
      summary: Create config
      description: |
        Creates a new config

        **Auth:** Requires valid admin token with one of the following permissions:
        - `update_configs_<name>`
        - `all_configs_<name>`
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_admin_req_update_configs'
            examples:
              system:
                summary: System-wide config
                value:
                  type: config_type
                  all_apps: true
                  all_orgs: true
                  system: true
                  data:
                    example_env: example
              org_admin:
                summary: Organization-wide config
                value:
                  type: config_type
                  all_apps: true
                  all_orgs: false
                  system: false
                  data:
                    example_env: example
              app_org_specific:
                summary: Application organization specific config
                value:
                  type: config_type
                  all_apps: false
                  all_orgs: false
                  system: false
                  data:
                    example_env: example
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-core-function: CreateConfig
      x-data-type: common.Config
      x-authentication-type: Permissions
      x-conversion-function: configFromRequest
  '/api/admin/configs/{id}':
    get:
      tags:
        - Admin
      summary: Get config
      description: |
        Gets config record

        **Auth:** Requires valid admin token with one of the following permissions:
        - `get_configs_<name>`
        - `update_configs_<name>`
        - `delete_configs_<name>`
        - `all_configs_<name>`
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of config to retrieve
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-core-function: GetConfig
      x-data-type: common.Config
      x-authentication-type: Permissions
    put:
      tags:
        - Admin
      summary: Update config
      description: |
        Updates existing config record

        **Auth:** Requires valid admin token with one of the following permissions:
        - `update_configs_<name>`
        - `all_configs_<name>`
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of config to update
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: New config content
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_admin_req_update_configs'
            examples:
              system:
                summary: System-wide config
                value:
                  type: config_type
                  all_apps: true
                  all_orgs: true
                  system: true
                  data:
                    example_env: example
              org_admin:
                summary: Organization-wide config
                value:
                  type: config_type
                  all_apps: true
                  all_orgs: false
                  system: false
                  data:
                    example_env: example
              app_org_specific:
                summary: Application organization specific config
                value:
                  type: config_type
                  all_apps: false
                  all_orgs: false
                  system: false
                  data:
                    example_env: example
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-core-function: UpdateConfig
      x-data-type: common.Config
      x-authentication-type: Permissions
      x-conversion-function: configFromRequest
    delete:
      tags:
        - Admin
      summary: Delete config
      description: |
        Deletes config record

        **Auth:** Requires valid admin token with one of the following permissions:
        - `delete_configs_<name>`
        - `all_configs_<name>`
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of config to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-core-function: DeleteConfig
      x-data-type: common.Config
      x-authentication-type: Permissions
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Config:
      required:
        - id
        - type
        - app_id
        - org_id
        - system
        - data
        - date_created
        - date_updated
      type: object
      properties:
        id:
          readOnly: true
          type: string
        type:
          type: string
        app_id:
          readOnly: true
          type: string
        org_id:
          readOnly: true
          type: string
        system:
          type: boolean
        data:
          type: object
          additionalProperties: true
        date_created:
          readOnly: true
          type: string
        date_updated:
          readOnly: true
          type: string
          nullable: true
    _admin_req_update_configs:
      required:
        - type
        - all_apps
        - all_orgs
        - system
        - data
      type: object
      properties:
        type:
          type: string
        all_apps:
          writeOnly: true
          type: boolean
        all_orgs:
          writeOnly: true
          type: boolean
        system:
          type: boolean
        data:
          type: object
          additionalProperties: true
